name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
            echo "VM_SSH_KEY is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.VM_HOST }}" ]; then
            echo "VM_HOST is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "VM_USER is not set!"
            exit 1
          fi
        shell: bash


      - name: Execute SSH commands on the VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/Project/Formularios_Georreferenciados
            git pull origin main
